[tool.poetry]
name = "backend-challenge"
version = "0.1.0"
description = ""
authors = ["Nikolas Schriefer <info@nikolasschriefer.de>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^2.3.2"
flask-cors = "^3.0.8"
flask-migrate = "^2.5.3"
flask-script = "^2.0.6"
flask-sqlalchemy = "^2.4.3"
psycopg2-binary = "^2.8.5"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.14.0"
flake8 = "^3.8.3"
coverage = "^5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
